### ISSUE TITLE
New Doc: A new starter kit for React and Adobe Twist

### ISSUE THREAD

**Issue by sangupta** [adobe/twist#16]
Hi - this is not a bug report, but a starter kit repo for getting started with React and Adobe Twist. Please review and see if its OK to mention it on the page: https://github.com/adobe/twist/blob/master/docs/getting-started/starter-projects.md

Starter Kit: https://github.com/sangupta/react-twist-base

**Comment by kerrishotts** [comment]
That's awesome! Would you mind creating a PR with a link to your starter kit? That way you can have credit for contributing back to the project as well :-)

**Comment by sangupta** [comment]
Hi @kerrishotts - Created PR #17 for the same. Thanks!

**Comment by lanther** [comment]
This is a great start! We'll need to do some work on automatic project generation (something like create-react-app), like we had for Torq, but in the meantime example repos are a great way to help people get started!

I'll close this issue, since I merged your PR - we can open another for the project generation work.
